//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoBenner
{
    using System;
    using System.Collections.Generic;
    
    public partial class preco
    {
        public int id_preco { get; set; }
        public Nullable<double> preco1 { get; set; }
    }
}
